// <auto-generated />
using CSLLMCapstone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSLLMCapstone.Migrations
{
    [DbContext(typeof(StudyContext))]
    [Migration("20260128072738_SeedUniversityCatalog")]
    partial class SeedUniversityCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CSLLMCapstone.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 102,
                            CourseDesc = "test desc",
                            Title = "Health and Technology"
                        },
                        new
                        {
                            CourseId = 105,
                            CourseDesc = "test desc",
                            Title = "The Logical Basis of Computing"
                        },
                        new
                        {
                            CourseId = 107,
                            CourseDesc = "test desc",
                            Title = "Make a Game with Computer Science"
                        },
                        new
                        {
                            CourseId = 109,
                            CourseDesc = "test desc",
                            Title = "Quantitative Reasoning Using Python"
                        },
                        new
                        {
                            CourseId = 110,
                            CourseDesc = "test desc",
                            Title = "Programming Fundamentals I"
                        },
                        new
                        {
                            CourseId = 111,
                            CourseDesc = "test desc",
                            Title = "Programming Fundamentals II"
                        },
                        new
                        {
                            CourseId = 112,
                            CourseDesc = "test desc",
                            Title = "Introduction to Data Science in Python"
                        },
                        new
                        {
                            CourseId = 301,
                            CourseDesc = "test desc",
                            Title = "Data Structures"
                        },
                        new
                        {
                            CourseId = 302,
                            CourseDesc = "test desc",
                            Title = "Advanced Data Structures and File Processing"
                        },
                        new
                        {
                            CourseId = 311,
                            CourseDesc = "test desc",
                            Title = "Computer Architecture I"
                        },
                        new
                        {
                            CourseId = 312,
                            CourseDesc = "test desc",
                            Title = "Computer Architecture II"
                        },
                        new
                        {
                            CourseId = 325,
                            CourseDesc = "test desc",
                            Title = "Technical Writing in Computer Science"
                        },
                        new
                        {
                            CourseId = 351,
                            CourseDesc = "test desc",
                            Title = "Web Development Technologies II"
                        },
                        new
                        {
                            CourseId = 361,
                            CourseDesc = "test desc",
                            Title = "Principles of Language Design I"
                        },
                        new
                        {
                            CourseId = 362,
                            CourseDesc = "test desc",
                            Title = "Principles of Language Design II"
                        },
                        new
                        {
                            CourseId = 367,
                            CourseDesc = "test desc",
                            Title = "Advanced Visual Basic Programming"
                        },
                        new
                        {
                            CourseId = 370,
                            CourseDesc = "test desc",
                            Title = "Introduction to Linux"
                        },
                        new
                        {
                            CourseId = 380,
                            CourseDesc = "test desc",
                            Title = "Introduction to Software Engineering"
                        },
                        new
                        {
                            CourseId = 420,
                            CourseDesc = "test desc",
                            Title = "Database Management Systems"
                        },
                        new
                        {
                            CourseId = 427,
                            CourseDesc = "test desc",
                            Title = "Algorithm Analysis"
                        },
                        new
                        {
                            CourseId = 428,
                            CourseDesc = "test desc",
                            Title = "Introduction to Graph Algorithm"
                        },
                        new
                        {
                            CourseId = 430,
                            CourseDesc = "test desc",
                            Title = "Cybersecurity"
                        },
                        new
                        {
                            CourseId = 440,
                            CourseDesc = "test desc",
                            Title = "Computer Graphics"
                        },
                        new
                        {
                            CourseId = 445,
                            CourseDesc = "test desc",
                            Title = "Data and Information Visualization"
                        },
                        new
                        {
                            CourseId = 446,
                            CourseDesc = "test desc",
                            Title = "User Interface Design and Development"
                        },
                        new
                        {
                            CourseId = 450,
                            CourseDesc = "test desc",
                            Title = "Computer Network and Data Communications"
                        },
                        new
                        {
                            CourseId = 452,
                            CourseDesc = "test desc",
                            Title = "Ethical Hacking and Penetration Testing for Computer Science"
                        },
                        new
                        {
                            CourseId = 456,
                            CourseDesc = "test desc",
                            Title = "Data Mining"
                        },
                        new
                        {
                            CourseId = 457,
                            CourseDesc = "test desc",
                            Title = "Computational Intelligence and Machine Learning"
                        },
                        new
                        {
                            CourseId = 460,
                            CourseDesc = "test desc",
                            Title = "Software Engineering for Mobile Devices"
                        },
                        new
                        {
                            CourseId = 465,
                            CourseDesc = "test desc",
                            Title = "Scientific Computing"
                        },
                        new
                        {
                            CourseId = 466,
                            CourseDesc = "test desc",
                            Title = "Virtual Reality"
                        },
                        new
                        {
                            CourseId = 467,
                            CourseDesc = "test desc",
                            Title = "Computational Statistics"
                        },
                        new
                        {
                            CourseId = 470,
                            CourseDesc = "test desc",
                            Title = "Operating Systems"
                        },
                        new
                        {
                            CourseId = 471,
                            CourseDesc = "test desc",
                            Title = "Optimization"
                        },
                        new
                        {
                            CourseId = 473,
                            CourseDesc = "test desc",
                            Title = "Parallel Computing"
                        },
                        new
                        {
                            CourseId = 480,
                            CourseDesc = "test desc",
                            Title = "Advanced Software Engineering"
                        },
                        new
                        {
                            CourseId = 481,
                            CourseDesc = "test desc",
                            Title = "Capstone Project"
                        },
                        new
                        {
                            CourseId = 489,
                            CourseDesc = "test desc",
                            Title = "Senior Colloquium"
                        });
                });

            modelBuilder.Entity("CSLLMCapstone.Models.Instance", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId");

                    b.HasIndex("UserId");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("CSLLMCapstone.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId");

                    b.HasIndex("CourseId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            CourseId = 102,
                            Name = "Big Tech",
                            TopicDesc = "test desc"
                        },
                        new
                        {
                            TopicId = 2,
                            CourseId = 102,
                            Name = "Video Games",
                            TopicDesc = "test desc"
                        },
                        new
                        {
                            TopicId = 3,
                            CourseId = 102,
                            Name = "Telemedicine",
                            TopicDesc = "test desc"
                        },
                        new
                        {
                            TopicId = 4,
                            CourseId = 102,
                            Name = "AI",
                            TopicDesc = "test desc"
                        },
                        new
                        {
                            TopicId = 5,
                            CourseId = 102,
                            Name = "Robotis",
                            TopicDesc = "test desc"
                        },
                        new
                        {
                            TopicId = 6,
                            CourseId = 102,
                            Name = "Deep Web",
                            TopicDesc = "test desc"
                        },
                        new
                        {
                            TopicId = 7,
                            CourseId = 102,
                            Name = "VR",
                            TopicDesc = "test desc"
                        },
                        new
                        {
                            TopicId = 8,
                            CourseId = 102,
                            Name = "Music Technology",
                            TopicDesc = "test desc"
                        },
                        new
                        {
                            TopicId = 9,
                            CourseId = 102,
                            Name = "Wearables",
                            TopicDesc = "test desc"
                        },
                        new
                        {
                            TopicId = 10,
                            CourseId = 102,
                            Name = "Ethics",
                            TopicDesc = "test desc"
                        });
                });

            modelBuilder.Entity("CSLLMCapstone.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CwuEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int>("GraduationDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Minor")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("CwuEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CSLLMCapstone.Models.Instance", b =>
                {
                    b.HasOne("CSLLMCapstone.Models.User", "User")
                        .WithMany("Instances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSLLMCapstone.Models.Topic", b =>
                {
                    b.HasOne("CSLLMCapstone.Models.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CSLLMCapstone.Models.Course", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("CSLLMCapstone.Models.User", b =>
                {
                    b.Navigation("Instances");
                });
#pragma warning restore 612, 618
        }
    }
}
